services:
    web:
        image: gioco-php-fpm:8.2
        container_name: pp-php-fpm
        build: .
        restart: always
        volumes:
            - .:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        networks:
            - pp-network
        extra_hosts:
            - "host.docker.internal:host-gateway"
    nginx:
        image: nginx:alpine
        container_name: pp-nginx
        ports:
            - ${APP_LOCAL_PORT:-9522}:80
        restart: always
        volumes:
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
            - .:/var/www/html
        depends_on:
            - web
        networks:
            - pp-network

networks:
    pp-network:
        driver: bridge
